{% set name = "sardana-limaccd" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-limaccd/archive/{{ version }}.tar.gz
  sha256: 7386fddda81a2d3aee776a1326ffd4ea884970f48334165a7418df0baa85af44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sardana

test:
  imports:
    - sardana_limaccd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ALBA-Synchrotron/sardana-limaccd
  summary: LimaCCDs Tango plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
