{% set name = "sardana-limaccd" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-limaccd/archive/{{ version }}.tar.gz
  sha256: b5a1c0e015e58e39718d9d75e47184e028567fcaa728ab078e89998599fe9dff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sardana

test:
  imports:
    - sardana_limaccd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/sardana-limaccd
  summary: LimaCCDs Tango plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
