{% set name = "sardana-limaccd" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/sardana-org/sardana-limaccd/-/archive/{{ version }}/sardana-limaccd-{{ version }}.tar.gz
  sha256: dc53a04bd6e97dd85eeae16bac6d4a36c234c375af08b2b39fa9fd9eca4d5ab9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sardana

test:
  imports:
    - sardana_limaccd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/sardana-org/sardana-limaccd
  summary: LimaCCDs Tango plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
