schema_version: 1

context:
  name: sardana-limaccd
  version: "0.15.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 6a95e9ecd6e1095618120aef5d34e7bcfdc253290ab5af72f6e548b87ec153a0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - sardana

tests:
  - python:
      imports:
        - sardana_limaccd
      python_version: ["${{ python_min }}.*", "3.*"]
      pip_check: true

about:
  summary: LimaCCDs Tango plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/sardana-org/sardana-limaccd

extra:
  recipe-maintainers:
    - rhomspuron
    - ovallcorba
